import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        
      }}
    >
      <html lang='en'>
        <body
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            minHeight: "100vh",
            position: "relative",
            backgroundImage: "url('/assets/eyy.svg')",
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
          className={inter.className}
        >

           <img
            src="/assets/Design.svg"
            alt="Description of your image"
            style={{
              width: "120px", // Default width for larger screens
              height: "120px", // Default height for larger screens
              position: "absolute",
              top: "60px", // Adjust top position as needed
            }}
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
